### PR TITLE
Added factorial, cleaned up code, added eval() for higher functionality

### PR DESCRIPTION
**Pull request by Vyvy-vi**
@RohanDas28 
Kindly check and maybe merge PR.

*Feel free to ping me, if you need anything more!

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
P.S. - I also linted all the code

**Comment by Vyvy-vi** [comment]
Can this be like accepted... 
Last day for getting mature PRs

**Comment by RohanDas28** [comment]
Awesome work 👍

**Comment by Vyvy-vi** [comment]
Thanks!

**Pull request merged**
