### PR TITLE
Try and except for unfortunate errors or mishandled program

### PR DESCRIPTION
**Pull request by CodeRustyPro**

### CODE REVIEW

**Comment by RohanDas28** [comment]
It is not necessary for this simple program brother :)

**Comment by CodeRustyPro** [comment]
IT JUST WANTED TO MAKE A PULL REQUEST FOR HACKTOBER

**Comment by RohanDas28** [comment]
Bro check the rules they have changed the rules now.

**Comment by CodeRustyPro** [comment]
> Bro check the rules they have changed the rules now.

but if you accept they can accept it btw you accepted the same pull request of chinmoy

**Comment by RohanDas28** [comment]
> > Bro check the rules they have changed the rules now.
> 
> but if you accept they can accept it btw you accepted the same pull request of chinmoy

I have added the label Now it counts towards the hacktoberfest

**Comment by CodeRustyPro** [comment]
Will my request count now?

**Comment by RohanDas28** [comment]
Yes 🥳

**Comment by CodeRustyPro** [comment]
My order is confirmed and yours?

**Comment by RohanDas28** [comment]
No I did not received the link yet.

**Pull request closed without merging**
